Faster complex models
ska-sa/katsdppipelines pull request #404
Opened 2019-08-26 13:07 UTC by KimMcAlpine

Improve the performance of the pipeline's calculation of visibilities for complex models (models with multiple sources located away from the phase centre) as described in Jira ticket [SPR1-104](https://skaafrica.atlassian.net/browse/SPR1-104)

This is to allow the pipeline to incorporate these models when calculating the MeerKAT bandpass. The presence of sources away from the phase centre cause a 'ripple' modulation of the amplitude and phase of the visibilities which are more rapid on longer baselines. If not accounted for this could result in 'ripples' in the final computed bandpass. 

A few other minor changes are:
* If there is no default model for a source in the `/conf/sky_models` directory, the pipeline now uses the model provided by the target string
* The pipeline models are now provided for a MHz (not GHz) scale
* The spectrum of the dominant source in the model in now plotted in the `corrected_data` plots versus frequency in the cal report.

2019-08-27 07:08 UTC, bmerry requested changes
Here's a first batch of comments. I still need to review the report code and the tests.

2019-08-27 11:38 UTC, bmerry reviewed
I've reviewed the report code too now. I think it probably makes sense to wait for my current comments to be addressed before reviewing the tests in case they cause the tests to change.

2019-09-04 08:03 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +                        k_ant[t, c, p, a] = np.exp(2 * np.pi * 1j * phase / wl[c])
I've made the suggested changes

2019-09-04 08:04 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +        uvw co-ordinates of antennas
Yes, I've removed the polarisation axis the UVW and K parameters

2019-09-04 08:08 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +    Convert an array of per antenna complex gains to a per baseline array
I've incorporated this function into the `add_model_vis` function, so the docstring is slightly altered, but I have hyphenated "per antenna"

2019-09-04 08:12 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +                                             * np.conj(k_ant[t, c, p, ant2[b]]))
I've removed the polarisation axis from the model. I think its simplifies the code as we aren't really doing proper polarisation calculations at the moment. I've also updated the docstring to indicate that the model is calculated assuming that `S` is the  Stokes I flux density.

2019-09-04 08:14 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +        array of per antenna quantities
This function as been subsumed into the `add_model_vis` function so the docstring no longer exists

2019-09-04 08:14 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +        array to update with per baseline gains
Docstring is now obsolete

2019-09-04 08:14 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +        K-jones term per baseline
Capitalised

2019-09-04 09:24 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +    return model
In my test notebook implementing in numba (with parallel =True) was roughly 20 x faster than doing it in numpy. 
I have implemented your suggestion of combining the `ant_to_bls` and `add_model_vis` steps into one function.

2019-09-04 09:35 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +    n = np.sqrt(1 - l**2 - m**2)
Done

2019-09-04 09:42 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                    self.uvw = np.array(uvw, np.float32)
As discussed `self.target` is the `cbf_target` sensor which should be the phase centre of the array. The only possible wrinkle is there is an option to apply an offset to the pointing from the `cbf_target` but this is unlikely to be an option selected when observing a calibrator. So I'm leaving this as is for now.

2019-09-04 09:53 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +    Calculate the K-Jones term, i.e the fourier transform phase term,
I just meant it to be a reminder that K-Jones means the phase of the 2D Fourier transform between visibility and sky brightness. Sometimes its hard to remember which of Jones matrix is which :). I've altered the docstring to hopefully be a bit clearer.

2019-09-04 09:54 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                & (max(max_freq) < max(self.channel_freqs / 1e6)):
Yes you are correct, replaced with `or`

2019-09-04 14:06 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/pipelineprocs.py
>          model_components = np.genfromtxt(model_file, delimiter=',', dtype=model_dtype)
I've implemented this, but with a small caveat. If you read in the file as a katpoint catalogue you can't store the catalogue directly in telstate,  this requires you to convert the catalogue to a list of  target description strings. However this process of converting to a description string causes a loss in precision in the coefficients in the flux model which only stores 4 significant figures i.e 34. 6776 becomes 34.68.  

To avoid this I'm reading in the file as a list of description strings, which gets stored in telstate, and then converting the model to a catalogue using the `add_model` function.

2019-09-04 14:06 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/pipelineprocs.py
> +        model_list = [f for f in model_list if f[-1] != '~']
I've removed this

2019-09-04 14:11 UTC, bmerry commented on katsdpcal/katsdpcal/pipelineprocs.py
>          model_components = np.genfromtxt(model_file, delimiter=',', dtype=model_dtype)
Maybe we should just fix katpoint so that it doesn't throw away precision? It's probably a one-line fix and it'll no doubt cause problems elsewhere too.

2019-09-04 14:14 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                    # (so use frequencies in GHz)
removed comment

2019-09-04 14:19 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                    # (so use frequencies in GHz)
removed comment

2019-09-04 14:19 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/conf/sky_models/J0408-6545.txt
> +# Polarization angle for PKS0407-65 is assumed -25 degrees. Fractional polarization of
I've included the polarisation in the model now

2019-09-04 14:19 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/pipelineprocs.py
> +    name : :class:`katpoint.Target`
Changed

2019-09-04 14:20 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/conf/sky_models/3C286.txt
> +S0, P, 13:31:08.3, 30:30:33, 400, 50e3, 0.1823, 1.4757, -0.4739, 0.0336, 0, 0, 1, 0, 0, 0
I've included the polarisation in the model now

2019-09-04 14:22 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                     or self.model_raw_params['a3'] == 0)):
I'm using katpoint now, and checking that all the `coefs[1:6] == 0`

2019-09-04 14:30 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/report.py
> +        flux density in Jy
Done

2019-09-16 15:05 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +@numba.jit(nopython=True, parallel=True)
I'm setting the number of workers to the `self.num_workers` attribute of the Pipeline class. I have also set the numba `THREADING_LAYER` to `safe`. This should use the TBB  threading layer. I did a very simple test and I think TBB should work in the default container without any extra packages.

2019-09-16 15:11 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +            self.model = np.array([1], np.float32)
I  think it could be quite dangerous to throw out  only some sources in the model. The overall model could be very strongly biased by one or two strong sources in the field and throwing these out could result in a very poor model, certainly it could be just as different to the true sky model  as just using the dominant source in the field. So I think that unless all the sources in the sky model are correct its probably a good default to  use only the dominant source.

I've modified it now so that it will default to the dominant source, but if this also has a model which is not valid in the given frequency range it will fall back to 1Jy

2019-09-25 12:47 UTC, bmerry requested changes
It's looking much better - nice to see flux calculations finally leveraging katpoint. It's just minor niggles left.

Not entirely related to this PR, but I've heard on the grapevine that commissioning is standardising on J-names for target. Should the 3C* files be renamed to use those names?

2019-09-25 12:47 UTC, bmerry commented on katsdpcal/katsdpcal/test/test_control.py
> +        print(np.average(flux_density))
This looks like debug code you left in?

2019-09-25 12:47 UTC, bmerry commented on katsdpcal/katsdpcal/test/test_pipelineprocs.py
> +                           ' 5 6 7 8')
It's okay to make this a single line (the flake8 config sets a max length of 100), and I think more readable as one line. Also, shouldn't there be parentheses around the flux model?

2019-09-25 12:47 UTC, bmerry commented on katsdpcal/katsdpcal/test/test_pipelineprocs.py
> +            f.close()
It's preferred to use a `with` statement to ensure the file is closed; and since `self.file_model` doesn't itself have a newline, I would suggest using `print` rather than `write`:
```python
with open(fname, 'w') as f:
    print(self.file_model, file=f)
```

2019-09-25 12:47 UTC, bmerry commented on katsdpcal/katsdpcal/test/test_pipelineprocs.py
> +            f.close()
See comments above about writing model files.

2019-09-25 12:47 UTC, bmerry commented on katsdpcal/katsdpcal/test/test_pipelineprocs.py
> +
Remove this blank line (PEP 257).

2019-09-25 12:47 UTC, bmerry commented on katsdpcal/katsdpcal/test/test_calprocs.py
> +        expected_kant[1, 1, 3] = np.exp(2 * np.pi * 1j * (20 + (np.sqrt(0.95) - 1) / 0.4))
`2 * np.pi * 1j` can be more compactly written as `2j * np.pi`.

2019-09-25 12:47 UTC, bmerry commented on katsdpcal/katsdpcal/test/test_calprocs.py
> +        expected_kant[:, 0] = np.exp(2 * np.pi * 1j * (3 + (np.sqrt(0.95) - 1) / 0.1))
Would be clearer (and easier to change) if one wrote `n = np.sqrt(1 - l * l - m * m)` where `l` and `m` are set up and then used `n`.

2019-10-15 15:01 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/test/test_calprocs.py
> +        expected_kant[:, 0] = np.exp(2 * np.pi * 1j * (3 + (np.sqrt(0.95) - 1) / 0.1))
Yes, I've changed this as suggested

2019-10-15 15:02 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/test/test_calprocs.py
> +        expected_kant[1, 1, 3] = np.exp(2 * np.pi * 1j * (20 + (np.sqrt(0.95) - 1) / 0.4))
Yes, I've changed this as suggested

2019-10-15 15:06 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/test/test_pipelineprocs.py
> +
Removed

2019-10-15 15:07 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/test/test_pipelineprocs.py
> +            f.close()
Done

2019-10-15 15:07 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/test/test_pipelineprocs.py
> +            f.close()
Done

2019-10-15 15:07 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/test/test_pipelineprocs.py
> +                           ' 5 6 7 8')
I've made this a single line and included parentheses, but I think the parentheses are optional.

2019-10-15 15:09 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/test/test_control.py
> +        print(np.average(flux_density))
Oops, yes - I've removed it

2019-10-21 11:51 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +            self.model = complexmodel[:, :, np.newaxis, :]
Comment added

2019-10-21 11:52 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                complexmodel = calprocs.add_model_vis(k_ant[:, :,  :],
Removed `[:, :, :]`

2019-10-21 11:53 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                    self.channel_freqs / 1.0e6)
Yes, its now on one line

2019-10-21 11:57 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                source_flux = katpoint.FluxDensityModel(0, 100.0e3, coefs=I_coefs)
Changed to `source.flux_density(self.channel_freqs  / 1.0e6)`

2019-10-21 13:13 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                            np.mean(self.model)))
Using MHz in the log message

2019-10-21 13:14 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                    len(self.model_raw_params),))
Changed to %-style formatting

2019-10-21 13:21 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                    source_flux = katpoint.FluxDensityModel(0, 100.0e3, coefs=I_coefs)
Changed to use the FluxDensityModel of the source in the catalogue

2019-10-21 13:24 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                            self.model[0],))
Fair point, I've removed this case. Now there are only two a single point source at the phase centre with a spectral model or a full model.

2019-10-21 13:25 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                    'for part of the band, setting model flux to 1')
Changed to be a warning

2019-10-21 13:25 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +                ', selecting only the first source '
Changed to be a warning

2019-10-21 13:37 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +            return ~not_valid
Changed as suggested

2019-10-21 13:37 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/scan.py
> +            """ Check all models in model_cat are valid for the given freqs (in Hz) """
Spaces removed

2019-10-21 13:44 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/report.py
> +    If there is no model, returns None
Added an empty line

2019-10-21 13:48 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +    The K-Jones term is the phase term in the approximate
I've clarified that it is the geometric delay

2019-10-21 13:55 UTC, KimMcAlpine commented on katsdpcal/katsdpcal/calprocs.py
> +    valid_weights = np.where(~np.isfinite(x), 0, weights)
Changed as suggested

2019-10-22 09:33 UTC, bmerry requested changes
Looks fine - just the one place where you commented to say you'd changed the logging but the change doesn't seem to be there.

2019-10-22 09:33 UTC, bmerry commented on katsdpcal/katsdpcal/scan.py
> +                    len(self.model_raw_params),))
Did you forget to push it?

2019-10-22 12:39 UTC, KimMcAlpine commented
Sorry, just missed it. I've fixed it now

On Tue, Oct 22, 2019 at 11:33 AM Bruce Merry <notifications@github.com>
wrote:

> *@bmerry* requested changes on this pull request.
>
> Looks fine - just the one place where you commented to say you'd changed
> the logging but the change doesn't seem to be there.
> ------------------------------
>
> In katsdpcal/katsdpcal/scan.py
> <https://github.com/ska-sa/katsdppipelines/pull/404#discussion_r337414168>
> :
>
> >          # CASE C - Complex model requiring calculation via uvw coordinates ####
>          # If not one of the simple cases above, make a proper full model
>          else:
>              self.logger.info(
> -                '     Model: {0} point sources'.format(len(np.atleast_1d(self.model_raw_params)),))
> +                '     Model: {0} point sources'.format(
> +                    len(self.model_raw_params),))
>
> Did you forget to push it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ska-sa/katsdppipelines/pull/404?email_source=notifications&email_token=ACMD2WJTV2XUIRLOGIAHXFTQP3CFRA5CNFSM4IPPPJX2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCIXQG6I#pullrequestreview-305070969>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACMD2WNOV7E4YY4TSAC732TQP3CFRANCNFSM4IPPPJXQ>
> .
>

2019-10-22 13:13 UTC, bmerry approved these changes

2019-10-22 13:19 UTC, merged